spring:
  application:
    name: "CART-SERVICE"
  profiles:
    active: mcprofile

  # H2 database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:magazin         # будем использовать БД в памяти.
    username: sa
    password:
  # консоль для отладки
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # автозапуск schema.sql
  sql:
    init:
      mode: always

  # Spring Jpa Hibernate
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false
        format_sql: true

    generate-ddl: true

  config:
    import: optional:configserver:http://localhost:8888


