spring:
  application:
    name: "PAYMENT-SERVICE"
  profiles:
    active: mcprofile

  # H2 database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:magazin
    username: sa
    password:
  # Spring Jpa Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true

  # автозапуск скриптов 'schema.sql' и 'data.sql'
  sql:
    init:
      mode: never           # не нужен
  # консоль для отладки
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


  config:
    import: optional:configserver:http://localhost:8888

