spring:
  application:
    name: "EUREKA-SERVER"
  profiles:
    active: default         # чтобы не подхватил общие настройки в профиле mcprofile

  config:
    import: optional:configserver:http://localhost:8888    # адрес сервера конфигурации